# Generated by Django 5.2.16 on 2026-09-10 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_imports", "0001_initial"),
        ("users", "0032_automationcredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunkeduploadsession",
            name="automation_credential",
            field=models.ForeignKey(
                blank=True,
                help_text="Automation owner; rotation preserves this identity.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="users.automationcredential",
            ),
        ),
    ]
