# Generated by Django 5.2.16 on 2026-09-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0103_alter_authorityfrontier_authority_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding",
            name="configuration",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
