# Generated by Django 5.2.16 on 2026-09-15 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0104_embedding_configuration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorityPackArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pack_id", models.CharField(db_index=True, max_length=64)),
                ("fingerprint", models.CharField(max_length=71)),
                ("digest", models.CharField(max_length=64)),
                ("version", models.CharField(max_length=128)),
                ("directory_name", models.CharField(max_length=128)),
                (
                    "archive",
                    models.FileField(upload_to="authority_pack_artifacts/%Y/%m/"),
                ),
                ("contains_code", models.BooleanField(default=False)),
                ("declarations", models.JSONField(default=list)),
                ("charters", models.JSONField(default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorityPackActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pack_id", models.CharField(max_length=64, unique=True)),
                ("corpus_ids", models.JSONField(default=list)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "attempted_fingerprint",
                    models.CharField(blank=True, default="", max_length=71),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "active_artifact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="annotations.authoritypackartifact",
                    ),
                ),
            ],
        ),
    ]
