# Generated by Django 5.2.16 on 2026-09-15 00:56

import django.db.models.deletion
from django.db import migrations, models


def backfill_receipt_owners(apps, schema_editor):
    Upload = apps.get_model("worker_uploads", "WorkerDocumentUpload")
    Token = apps.get_model("worker_uploads", "CorpusAccessToken")
    owner = Token.objects.filter(pk=models.OuterRef("corpus_access_token_id")).values(
        "worker_account_id"
    )[:1]
    Upload.objects.filter(corpus_access_token__isnull=False).update(
        worker_account_id=models.Subquery(owner)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0060_corpus_default_agent"),
        ("worker_uploads", "0006_corpusaccesstoken_can_push_authority_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerdocumentupload",
            name="client_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="workerdocumentupload",
            name="error_history",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="workerdocumentupload",
            name="payload_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="workerdocumentupload",
            name="processing_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workerdocumentupload",
            name="processing_token",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="workerdocumentupload",
            name="worker_account",
            field=models.ForeignKey(
                help_text="Stable receipt owner across token rotation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="worker_uploads.workeraccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="workerdocumentupload",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_key__isnull", False)),
                fields=("worker_account", "corpus", "client_key"),
                name="unique_worker_upload_client_key",
            ),
        ),
        migrations.RunPython(backfill_receipt_owners, migrations.RunPython.noop),
    ]
