# Generated by Django 5.2.16 on 2026-09-15 02:12

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0060_corpus_default_agent"),
        ("worker_uploads", "0007_idempotency_and_recovery"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy", models.JSONField()),
                ("policy_digest", models.CharField(max_length=64)),
                ("ceiling_usd", models.DecimalField(decimal_places=9, max_digits=20)),
                (
                    "accounted_usd",
                    models.DecimalField(decimal_places=9, default=0, max_digits=20),
                ),
                (
                    "reserved_usd",
                    models.DecimalField(decimal_places=9, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("BUDGET_EXHAUSTED", "Budget Exhausted"),
                            ("POLICY_VIOLATION", "Policy Violation"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=24,
                    ),
                ),
                ("last_error", models.CharField(blank=True, max_length=64)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="corpuses.corpus",
                    ),
                ),
                (
                    "worker_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="worker_uploads.workeraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngestionOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=16)),
                ("target_id", models.PositiveBigIntegerField()),
                ("input_digest", models.CharField(max_length=64)),
                ("estimated_usd", models.DecimalField(decimal_places=9, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("UNCERTAIN", "Uncertain"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="WAITING",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="worker_uploads.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workerdocumentupload",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploads",
                to="worker_uploads.ingestionrun",
            ),
        ),
        migrations.CreateModel(
            name="IngestionRunEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("detail", models.JSONField(default=dict)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="worker_uploads.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngestionReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt", models.PositiveIntegerField()),
                ("amount_usd", models.DecimalField(decimal_places=9, max_digits=20)),
                (
                    "accounted_usd",
                    models.DecimalField(decimal_places=9, max_digits=20, null=True),
                ),
                ("accounted_tokens", models.PositiveIntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Reserved"),
                            ("STARTED", "Started"),
                            ("SETTLED", "Settled"),
                            ("UNCERTAIN", "Uncertain"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="RESERVED",
                        max_length=16,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("started", models.DateTimeField(null=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="worker_uploads.ingestionoperation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operation", "attempt"), name="ingest_attempt_once"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("accounted_usd__gte", 0), ("reserved_usd__gte", 0)),
                name="ingest_run_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "ceiling_usd__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("accounted_usd"), "+", models.F("reserved_usd")
                        ),
                    )
                ),
                name="ingest_run_within_ceiling",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionoperation",
            constraint=models.UniqueConstraint(
                fields=("run", "key"), name="ingest_operation_once"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionoperation",
            index=models.Index(
                fields=["run", "status"], name="ingestion_run_op_status"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionreservation",
            index=models.Index(
                fields=["created"],
                condition=models.Q(status="RESERVED"),
                name="ingestion_reserved_created",
            ),
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION protect_ingestion_run_policy() RETURNS trigger AS $$
            BEGIN
                IF OLD.policy IS DISTINCT FROM NEW.policy
                   OR OLD.policy_digest IS DISTINCT FROM NEW.policy_digest
                   OR OLD.worker_account_id IS DISTINCT FROM NEW.worker_account_id
                   OR OLD.corpus_id IS DISTINCT FROM NEW.corpus_id THEN
                    RAISE EXCEPTION 'ingestion run policy is immutable' USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END; $$ LANGUAGE plpgsql;
            CREATE TRIGGER ingestion_run_policy_immutable BEFORE UPDATE ON worker_uploads_ingestionrun
                FOR EACH ROW EXECUTE FUNCTION protect_ingestion_run_policy();
            CREATE FUNCTION protect_ingestion_run_binding() RETURNS trigger AS $$
            BEGIN
                IF OLD.ingestion_run_id IS DISTINCT FROM NEW.ingestion_run_id THEN
                    RAISE EXCEPTION 'ingestion run binding is immutable' USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END; $$ LANGUAGE plpgsql;
            CREATE TRIGGER upload_ingestion_run_immutable BEFORE UPDATE ON worker_uploads_workerdocumentupload
                FOR EACH ROW EXECUTE FUNCTION protect_ingestion_run_binding();
            CREATE FUNCTION protect_ingestion_operation_identity() RETURNS trigger AS $$
            BEGIN
                IF ROW(OLD.run_id, OLD.key, OLD.target_type, OLD.target_id, OLD.input_digest, OLD.estimated_usd)
                   IS DISTINCT FROM ROW(NEW.run_id, NEW.key, NEW.target_type, NEW.target_id, NEW.input_digest, NEW.estimated_usd) THEN
                    RAISE EXCEPTION 'ingestion operation identity is immutable' USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END; $$ LANGUAGE plpgsql;
            CREATE TRIGGER ingestion_operation_immutable BEFORE UPDATE ON worker_uploads_ingestionoperation
                FOR EACH ROW EXECUTE FUNCTION protect_ingestion_operation_identity();
            CREATE FUNCTION protect_ingestion_reservation_identity() RETURNS trigger AS $$
            BEGIN
                IF ROW(OLD.operation_id, OLD.attempt, OLD.amount_usd)
                   IS DISTINCT FROM ROW(NEW.operation_id, NEW.attempt, NEW.amount_usd) THEN
                    RAISE EXCEPTION 'ingestion reservation identity is immutable' USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END; $$ LANGUAGE plpgsql;
            CREATE TRIGGER ingestion_reservation_immutable BEFORE UPDATE ON worker_uploads_ingestionreservation
                FOR EACH ROW EXECUTE FUNCTION protect_ingestion_reservation_identity();
            """,
            """
            DROP TRIGGER upload_ingestion_run_immutable ON worker_uploads_workerdocumentupload;
            DROP TRIGGER ingestion_operation_immutable ON worker_uploads_ingestionoperation;
            DROP FUNCTION protect_ingestion_operation_identity();
            DROP TRIGGER ingestion_reservation_immutable ON worker_uploads_ingestionreservation;
            DROP FUNCTION protect_ingestion_reservation_identity();
            DROP FUNCTION protect_ingestion_run_binding();
            DROP TRIGGER ingestion_run_policy_immutable ON worker_uploads_ingestionrun;
            DROP FUNCTION protect_ingestion_run_policy();
            """,
        ),
    ]
