# Generated by Django 5.2.16 on 2026-09-15 00:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("worker_uploads", "0006_corpusaccesstoken_can_push_authority_sections"),
        ("corpuses", "0060_corpus_default_agent"),
        ("documents", "0043_add_file_converter_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingRepair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker_token",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worker_uploads.corpusaccesstoken",
                    ),
                ),
                ("generation", models.CharField(max_length=64)),
                ("status", models.CharField(default="queued", max_length=16)),
                ("requested", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished", models.DateTimeField(null=True)),
                ("attempted", models.PositiveIntegerField(default=0)),
                ("succeeded", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                (
                    "corpus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corpuses.corpus",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
            ],
        ),
    ]
