# Generated by Django 5.2.16 on 2026-09-15 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0045_worker_copy_processing_status"),
        ("worker_uploads", "0008_ingestion_run_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="worker_uploads.ingestionrun",
            ),
        ),
        migrations.RunSQL(
            "CREATE TRIGGER document_ingestion_run_immutable BEFORE UPDATE ON documents_document "
            "FOR EACH ROW EXECUTE FUNCTION protect_ingestion_run_binding();",
            "DROP TRIGGER document_ingestion_run_immutable ON documents_document;",
        ),
    ]
